// Code generated by lcryptogen: allocation-free variants of functions in x:internal/poly1305. DO NOT EDIT.

package poly1305

// NewInto is the allocation-free [New]: it initializes m instead of a new MAC.
func NewInto(m *MAC, key *[32]byte) *MAC {
	*m = MAC{}
	initialize(key, &m.macState)
	return m
}
