// Code generated by lcryptogen: allocation-free variants of functions in go:crypto/internal/fips140/sha3. DO NOT EDIT.

package sha3

// New224Into is the allocation-free [New224]: it initializes into instead of a new Digest.
func New224Into(into *Digest) *Digest {
	*into = Digest{}
	into.rate = rateK448
	into.outputLen = 28
	into.dsbyte = dsbyteSHA3
	return into
}

// New256Into is the allocation-free [New256]: it initializes into instead of a new Digest.
func New256Into(into *Digest) *Digest {
	*into = Digest{}
	into.rate = rateK512
	into.outputLen = 32
	into.dsbyte = dsbyteSHA3
	return into
}

// New384Into is the allocation-free [New384]: it initializes into instead of a new Digest.
func New384Into(into *Digest) *Digest {
	*into = Digest{}
	into.rate = rateK768
	into.outputLen = 48
	into.dsbyte = dsbyteSHA3
	return into
}

// New512Into is the allocation-free [New512]: it initializes into instead of a new Digest.
func New512Into(into *Digest) *Digest {
	*into = Digest{}
	into.rate = rateK1024
	into.outputLen = 64
	into.dsbyte = dsbyteSHA3
	return into
}

// NewLegacyKeccak256Into is the allocation-free [NewLegacyKeccak256]: it initializes into instead of a new Digest.
func NewLegacyKeccak256Into(into *Digest) *Digest {
	*into = Digest{}
	into.rate = rateK512
	into.outputLen = 32
	into.dsbyte = dsbyteKeccak
	return into
}

// NewLegacyKeccak512Into is the allocation-free [NewLegacyKeccak512]: it initializes into instead of a new Digest.
func NewLegacyKeccak512Into(into *Digest) *Digest {
	*into = Digest{}
	into.rate = rateK1024
	into.outputLen = 64
	into.dsbyte = dsbyteKeccak
	return into
}

// NewShake128Into is the allocation-free [NewShake128]: it initializes into instead of a new SHAKE.
func NewShake128Into(into *SHAKE) *SHAKE {
	*into = SHAKE{}
	into.d = Digest{rate: rateK256, outputLen: 32, dsbyte: dsbyteShake}
	return into
}

// NewShake256Into is the allocation-free [NewShake256]: it initializes into instead of a new SHAKE.
func NewShake256Into(into *SHAKE) *SHAKE {
	*into = SHAKE{}
	into.d = Digest{rate: rateK512, outputLen: 64, dsbyte: dsbyteShake}
	return into
}
