// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/nistec. DO NOT EDIT.

package nistec

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errInvalidP256CompressedPointEncoding = errors.New("invalid P256 compressed point encoding")
	errInvalidP256PointEncoding           = errors.New("invalid P256 point encoding")
	errP256PointNotOnCurve                = errors.New("P256 point not on curve")
	errP256PointIsThePoint                = errors.New("P256 point is the point at infinity")
	errInvalidScalarLength                = errors.New("invalid scalar length")
	errInvalidP384CompressedPointEncoding = errors.New("invalid P384 compressed point encoding")
	errInvalidP384PointEncoding           = errors.New("invalid P384 point encoding")
	errP384PointNotOnCurve                = errors.New("P384 point not on curve")
	errP384PointIsThePoint                = errors.New("P384 point is the point at infinity")
)
