// Code generated by lcryptogen: allocation-free variants of functions in go:crypto/internal/fips140/nistec. DO NOT EDIT.

package nistec

// NewP256PointInto is the allocation-free [NewP256Point]: it initializes p instead of a new P256Point.
func NewP256PointInto(p *P256Point) *P256Point {
	*p = P256Point{}
	p.y.One()
	return p
}

// BytesTo is the allocation-free [P256Point.Bytes]: it writes into out, which the
// result aliases, instead of a new array.
func (p *P256Point) BytesTo(out *[p256UncompressedLength]byte) []byte {
	return p.bytes(out)
}

// BytesXTo is the allocation-free [P256Point.BytesX]: it writes into out, which the
// result aliases, instead of a new array.
func (p *P256Point) BytesXTo(out *[p256ElementLength]byte) ([]byte, error) {
	return p.bytesX(out)
}

// BytesCompressedTo is the allocation-free [P256Point.BytesCompressed]: it writes into out, which the
// result aliases, instead of a new array.
func (p *P256Point) BytesCompressedTo(out *[p256CompressedLength]byte) []byte {
	return p.bytesCompressed(out)
}

// ProjectiveInto is the allocation-free [p256AffinePoint.Projective]: it initializes pp instead of a new P256Point.
func (p *p256AffinePoint) ProjectiveInto(pp *P256Point) *P256Point {
	*pp = P256Point{}
	pp.x = p.x
	pp.y = p.y
	pp.z.One()
	return pp
}
