// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen from go1.27.1 src/crypto/internal/fips140/ed25519/ed25519.go. DO NOT EDIT.

// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ed25519

import (
	"bytes"
	"unsafe"

	"github.com/soypat/lcrypto/internal/std/edwards25519"
	"github.com/soypat/lcrypto/internal/std/sha512"
)

const (
	seedSize       = 32
	publicKeySize  = 32
	privateKeySize = seedSize + publicKeySize
	signatureSize  = 64
	sha512Size     = 64
)

type PrivateKey struct {
	seed   [seedSize]byte
	pub    [publicKeySize]byte
	s      edwards25519.Scalar
	prefix [sha512Size / 2]byte
	sc     edwards25519.Scratch

	scratch scratchPrivateKey
}

// scratchPrivateKey holds locals hoisted out of function frames by lcryptogen
// so that they are never heap allocated. Not safe for concurrent use.
type scratchPrivateKey struct {
	h      sha512.Digest
	digest [sha512Size]byte
}

type PublicKey struct {
	a      edwards25519.Point
	aBytes [32]byte
	sc     edwards25519.Scratch

	scratch scratchPublicKey
}

// scratchPublicKey holds locals hoisted out of function frames by lcryptogen
// so that they are never heap allocated. Not safe for concurrent use.
type scratchPublicKey struct {
	h      sha512.Digest
	digest [sha512Size]byte
}

func newPrivateKeyFromSeed(priv *PrivateKey, seed []byte) (*PrivateKey, error) {
	if l := len(seed); l != seedSize {
		return nil, errBadSeedLength
	}
	copy(priv.seed[:], seed)
	precomputePrivateKey(priv)
	return priv, nil
}

func precomputePrivateKey(priv *PrivateKey) {
	hsObj := &priv.scratch.h
	*hsObj = sha512.Digest{}
	hs := sha512.NewInto(hsObj)
	hs.Write(priv.seed[:])
	hArr := &priv.scratch.digest
	*hArr = [sha512Size]byte{}
	h := hs.Sum(hArr[:0])

	s, err := priv.s.SetBytesWithClamping(h[:32])
	if err != nil {
		panic("ed25519: internal error: setting scalar failed")
	}
	A := (&edwards25519.Point{}).ScalarBaseMultScratch(s, &priv.sc)
	var bytesArr [32]byte
	copy(priv.pub[:], A.BytesTo(&bytesArr))

	copy(priv.prefix[:], h[32:])
}

func newPublicKey(pub *PublicKey, pubBytes []byte) (*PublicKey, error) {
	if l := len(pubBytes); l != publicKeySize {
		return nil, errBadPublicKeyLength
	}
	// SetBytes checks that the point is on the curve.
	if _, err := pub.a.SetBytes(pubBytes); err != nil {
		return nil, errBadPublicKey
	}
	copy(pub.aBytes[:], pubBytes)
	return pub, nil
}

// Domain separation prefixes used to disambiguate Ed25519/Ed25519ph/Ed25519ctx.
// See RFC 8032, Section 2 and Section 5.1.
const (
	// domPrefixPure is empty for pure Ed25519.
	domPrefixPure = ""
)

func sign(signature []byte, priv *PrivateKey, message []byte) []byte {
	return signWithDom(signature, priv, message, domPrefixPure, "")
}

func signWithDom(signature []byte, priv *PrivateKey, message []byte, domPrefix, context string) []byte {
	mhObj := &priv.scratch.h
	*mhObj = sha512.Digest{}
	mh := sha512.NewInto(mhObj)
	if domPrefix != domPrefixPure {
		mh.Write(unsafe.Slice(unsafe.StringData(domPrefix), len(domPrefix)))
		mh.Write([]byte{byte(len(context))})
		mh.Write(unsafe.Slice(unsafe.StringData(context), len(context)))
	}
	mh.Write(priv.prefix[:])
	mh.Write(message)
	messageDigestArr := &priv.scratch.digest
	*messageDigestArr = [sha512Size]byte{}
	messageDigest := messageDigestArr[:0]
	messageDigest = mh.Sum(messageDigest)
	var newScalarObj edwards25519.Scalar
	r, err := edwards25519.NewScalarInto(&newScalarObj).SetUniformBytes(messageDigest)
	if err != nil {
		panic("ed25519: internal error: setting scalar failed")
	}

	R := (&edwards25519.Point{}).ScalarBaseMultScratch(r, &priv.sc)

	khObj := &priv.scratch.h
	*khObj = sha512.Digest{}
	kh := sha512.NewInto(khObj)
	if domPrefix != domPrefixPure {
		kh.Write(unsafe.Slice(unsafe.StringData(domPrefix), len(domPrefix)))
		kh.Write([]byte{byte(len(context))})
		kh.Write(unsafe.Slice(unsafe.StringData(context), len(context)))
	}
	var bytesArr [32]byte
	kh.Write(R.BytesTo(&bytesArr))
	kh.Write(priv.pub[:])
	kh.Write(message)
	hramDigestArr := &priv.scratch.digest
	*hramDigestArr = [sha512Size]byte{}
	hramDigest := hramDigestArr[:0]
	hramDigest = kh.Sum(hramDigest)
	var newScalarObj2 edwards25519.Scalar
	k, err := edwards25519.NewScalarInto(&newScalarObj2).SetUniformBytes(hramDigest)
	if err != nil {
		panic("ed25519: internal error: setting scalar failed")
	}

	var SObj edwards25519.Scalar
	S := edwards25519.NewScalarInto(&SObj).MultiplyAdd(k, &priv.s, r)

	var bytesArr2 [32]byte
	copy(signature[:32], R.BytesTo(&bytesArr2))
	var bytesArr3 [32]byte
	copy(signature[32:], S.BytesTo(&bytesArr3))

	return signature
}

func verify(pub *PublicKey, message, sig []byte) error {
	return verifyWithDom(pub, message, sig, domPrefixPure, "")
}

func verifyWithDom(pub *PublicKey, message, sig []byte, domPrefix, context string) error {
	if l := len(sig); l != signatureSize {
		return errBadSignatureLength
	}

	if sig[63]&224 != 0 {
		return errInvalidSignature
	}

	khObj := &pub.scratch.h
	*khObj = sha512.Digest{}
	kh := sha512.NewInto(khObj)
	if domPrefix != domPrefixPure {
		kh.Write(unsafe.Slice(unsafe.StringData(domPrefix), len(domPrefix)))
		kh.Write([]byte{byte(len(context))})
		kh.Write(unsafe.Slice(unsafe.StringData(context), len(context)))
	}
	kh.Write(sig[:32])
	kh.Write(pub.aBytes[:])
	kh.Write(message)
	hramDigestArr := &pub.scratch.digest
	*hramDigestArr = [sha512Size]byte{}
	hramDigest := hramDigestArr[:0]
	hramDigest = kh.Sum(hramDigest)
	var newScalarObj edwards25519.Scalar
	k, err := edwards25519.NewScalarInto(&newScalarObj).SetUniformBytes(hramDigest)
	if err != nil {
		panic("ed25519: internal error: setting scalar failed")
	}

	var newScalarObj2 edwards25519.Scalar
	S, err := edwards25519.NewScalarInto(&newScalarObj2).SetCanonicalBytes(sig[32:])
	if err != nil {
		return errInvalidSignature
	}

	// [S]B = R + [k]A --> [k](-A) + [S]B = R
	minusA := (&edwards25519.Point{}).Negate(&pub.a)
	R := (&edwards25519.Point{}).VarTimeDoubleScalarBaseMultScratch(k, minusA, S, &pub.sc)

	var bytesArr [32]byte
	if !bytes.Equal(sig[:32], R.BytesTo(&bytesArr)) {
		return errInvalidSignature
	}
	return nil
}
