// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/ed25519. DO NOT EDIT.

package ed25519

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errBadSeedLength      = errors.New("ed25519: bad seed length")
	errBadPublicKeyLength = errors.New("ed25519: bad public key length")
	errBadPublicKey       = errors.New("ed25519: bad public key")
	errBadSignatureLength = errors.New("ed25519: bad signature length")
	errInvalidSignature   = errors.New("ed25519: invalid signature")
)
