// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen from go1.27.1 src/crypto/internal/fips140/sha256/sha256block_noasm.go. DO NOT EDIT.

// Copyright 2016 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sha256

func block(dig *Digest, p []byte) {
	blockGeneric(dig, p)
}
