// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen allocation-free variants of functions in go:crypto/internal/fips140/sha256. DO NOT EDIT.

package sha256

// NewInto is the allocation-free [New]: it initializes d instead of a new Digest.
func NewInto(d *Digest) *Digest {
	*d = Digest{}
	d.Reset()
	return d
}

// New224Into is the allocation-free [New224]: it initializes d instead of a new Digest.
func New224Into(d *Digest) *Digest {
	*d = Digest{}
	d.is224 = true
	d.Reset()
	return d
}
