// Code generated by lcryptogen: allocation-free variants of functions in go:crypto/internal/fips140/sha512. DO NOT EDIT.

package sha512

// NewInto is the allocation-free [New]: it initializes d instead of a new Digest.
func NewInto(d *Digest) *Digest {
	*d = Digest{}
	d.size = size512
	d.Reset()
	return d
}

// New512_224Into is the allocation-free [New512_224]: it initializes d instead of a new Digest.
func New512_224Into(d *Digest) *Digest {
	*d = Digest{}
	d.size = size224
	d.Reset()
	return d
}

// New512_256Into is the allocation-free [New512_256]: it initializes d instead of a new Digest.
func New512_256Into(d *Digest) *Digest {
	*d = Digest{}
	d.size = size256
	d.Reset()
	return d
}

// New384Into is the allocation-free [New384]: it initializes d instead of a new Digest.
func New384Into(d *Digest) *Digest {
	*d = Digest{}
	d.size = size384
	d.Reset()
	return d
}
