// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen from go1.27.1 src/crypto/internal/cryptotest/x509limbo/schemaversion.go. DO NOT EDIT.

// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by _schema/schema_gen.go, DO NOT EDIT.

package x509limbo

// X509LimboModule is the module path of the upstream x509-limbo project.
const X509LimboModule = "github.com/C2SP/x509-limbo"

// X509LimboVersion is the X509LimboModule version that schema.go was
// generated against.
const X509LimboVersion = "v0.0.0-20260522003327-feb7caccc1af"
