// Code generated by lcryptogen: errors.New calls hoisted from golang.org/x/crypto@v0.57.0 chacha20poly1305. DO NOT EDIT.

package chacha20poly1305

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errBadKeyLength = errors.New("chacha20poly1305: bad key length")
)
