// Code generated by lcryptogen: errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/mlkem. DO NOT EDIT.

package mlkem

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errUnreducedFieldElement         = errors.New("unreduced field element")
	errInvalidEncodingLength         = errors.New("mlkem: invalid encoding length")
	errInvalidPolynomialEncoding     = errors.New("mlkem: invalid polynomial encoding")
	errInvalidSeedLength             = errors.New("mlkem: invalid seed length")
	errInvalidEncapsulationKeyLength = errors.New("mlkem: invalid encapsulation key length")
	errInvalidCiphertextLength       = errors.New("mlkem: invalid ciphertext length")
)
