// Code generated by lcryptogen: allocation-free variants of functions in go:crypto/internal/fips140/mlkem. DO NOT EDIT.

package mlkem

// EncapsulationKeyInto is the allocation-free [DecapsulationKey768.EncapsulationKey]: it initializes into instead of a new EncapsulationKey768.
func (dk *DecapsulationKey768) EncapsulationKeyInto(into *EncapsulationKey768) *EncapsulationKey768 {
	*into = EncapsulationKey768{}
	into.ρ = dk.ρ
	into.h = dk.h
	into.encryptionKey = dk.encryptionKey
	return into
}

// GenerateKeyInternal768Into is the allocation-free [GenerateKeyInternal768]: it initializes dk instead of a new DecapsulationKey768.
func GenerateKeyInternal768Into(dk *DecapsulationKey768, d, z *[32]byte) *DecapsulationKey768 {
	*dk = DecapsulationKey768{}
	kemKeyGen(dk, d, z)
	return dk
}
