// Code generated by lcryptogen: errors.New calls hoisted from golang.org/x/crypto@v0.57.0 chacha20. DO NOT EDIT.

package chacha20

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errWrongKeySize            = errors.New("chacha20: wrong key size")
	errWrongNonceSize          = errors.New("chacha20: wrong nonce size")
	errWrongHChaCha20KeySize   = errors.New("chacha20: wrong HChaCha20 key size")
	errWrongHChaCha20NonceSize = errors.New("chacha20: wrong HChaCha20 nonce size")
)
