// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/aes/gcm. DO NOT EDIT.

package gcm

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errIncorrectTagSizeGivenTo   = errors.New("cipher: incorrect tag size given to GCM")
	errTheNonceCantHaveZero      = errors.New("cipher: the nonce can't have zero length")
	errNewGCMRequires128BitBlock = errors.New("cipher: NewGCM requires 128-bit block cipher")
)
