// Code generated by lcryptogen from go1.27.1 src/crypto/internal/fips140/aes/gcm/interface_test.go. DO NOT EDIT.

// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gcm_test

import (
	"crypto/cipher"
	"github.com/soypat/lcrypto/internal/std/gcm"
)

var _ cipher.AEAD = (*gcm.GCM)(nil)
