// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen from go1.27.1 src/crypto/internal/cryptotest/allocations.go. DO NOT EDIT.

// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package cryptotest

import (
	"github.com/soypat/lcrypto/internal/lcryptotest/testenv"
	"runtime"
	"testing"
)

// SkipTestAllocations skips the test if there are any factors that interfere
// with allocation optimizations.
func SkipTestAllocations(t *testing.T) {

	// The sanitizers sometimes cause allocations.
	if testenv.SanitizersEnabled {
		t.Skip("skipping allocations test with sanitizers")
	}

	// The plan9 crypto/rand allocates.
	if runtime.GOOS == "plan9" {
		t.Skip("skipping allocations test on plan9")
	}

	// s390x deviates from other assembly implementations and is very hard to
	// test due to the lack of LUCI builders. See #67307.
	if runtime.GOARCH == "s390x" {
		t.Skip("skipping allocations test on s390x")
	}

	// Some APIs rely on inliner and devirtualization to allocate on the stack.
	testenv.SkipIfOptimizationOff(t)
}
