// Code generated by lcryptogen: errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/bigmod. DO NOT EDIT.

package bigmod

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errInputOverflowsTheModulus     = errors.New("input overflows the modulus")
	errInputOverflowsTheModulusSize = errors.New("input overflows the modulus size")
	errModulusMustBe1               = errors.New("modulus must be > 1")
	errAOrMIsZero                   = errors.New("extendedGCD: a or m is zero")
	errBothAAndMAre                 = errors.New("extendedGCD: both a and m are even")
)
