// Code generated by lcryptogen: field array accessors for go1.27.1 src/crypto/internal/fips140/bigmod. DO NOT EDIT.

package bigmod

// lim returns the limbs in use, a slice of x's array.
func (x *Nat) lim() []uint { return x.limbs[:x.nlimbs] }

// natFromLimbs returns a new Nat holding a copy of limbs. It panics if limbs does not fit.
func natFromLimbs(limbs []uint) *Nat {
	x := &Nat{nlimbs: len(limbs)}
	copy(x.limbs[:len(limbs)], limbs)
	return x
}
