// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen allocation-free variants of functions in go:crypto/internal/fips140/bigmod. DO NOT EDIT.

package bigmod

// NewNatInto is the allocation-free [NewNat]: it initializes into instead of a new Nat.
func NewNatInto(into *Nat) *Nat {
	*into = Nat{}
	return into
}

// NatInto is the allocation-free [Modulus.Nat]: it initializes n instead of a new Nat.
func (m *Modulus) NatInto(n *Nat) *Nat {
	NewNatInto(n)
	n.set(m.nat)
	return n
}

// natFromLimbsInto is the allocation-free [natFromLimbs]: it initializes x instead of a new Nat.
func natFromLimbsInto(x *Nat, limbs []uint) *Nat {
	*x = Nat{}
	x.nlimbs = len(limbs)
	copy(x.limbs[:len(limbs)], limbs)
	return x
}
