// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/edwards25519/field. DO NOT EDIT.

package field

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errInvalidFieldElementInputSize = errors.New("edwards25519: invalid field element input size")
)
