// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen from go1.27.1 src/crypto/internal/fips140/edwards25519/field/fe_amd64_noasm.go. DO NOT EDIT.

// Copyright (c) 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package field

func feMul(v, x, y *Element) { feMulGeneric(v, x, y) }
