// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen allocation-free variants of functions in go:crypto/internal/fips140/edwards25519/field. DO NOT EDIT.

package field

// BytesTo is the allocation-free [Element.Bytes]: it writes into out, which the
// result aliases, instead of a new array.
func (v *Element) BytesTo(out *[32]byte) []byte {
	return v.bytes(out)
}
