// Code generated by lcryptogen: declarations added to go1.27.1 src/crypto/internal/fips140/rsa. DO NOT EDIT.

package rsa

import (
	"github.com/soypat/lcrypto/internal/std/bigmod"
)

// maxModulusBytes is the size of the largest modulus bigmod holds.
const maxModulusBytes = bigmod.MaxBits / 8

// rsaScratch holds buffers that would otherwise escape through hash.Hash or be
// heap allocated; lcryptogen hoists them here.
type rsaScratch struct {
	scratch scratchRsaScratch
}

// scratchRsaScratch holds locals hoisted out of function frames by lcryptogen
// so that they are never heap allocated. Not safe for concurrent use.
type scratchRsaScratch struct {
	em      [maxModulusBytes]byte
	prefix  [8]byte
	h0      [64]byte
	counter [4]byte
	digest  [64]byte
}
