// Code generated by lcryptogen: errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/rsa. DO NOT EDIT.

package rsa

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errUnsupportedHashFunction         = errors.New("crypto/rsa: unsupported hash function")
	errHashedMessageLengthDoesNot      = errors.New("crypto/rsa: hashed message length does not match hash function")
	errInternalErrorInconsistentLength = errors.New("rsa: internal error: inconsistent length")
	errMissingPublicModulus            = errors.New("crypto/rsa: missing public modulus")
	errPublicModulusIsEven             = errors.New("crypto/rsa: public modulus is even")
	errPublicExponentTooSmallOr        = errors.New("crypto/rsa: public exponent too small or negative")
	errPublicExponentIsEven            = errors.New("crypto/rsa: public exponent is even")
	errPublicExponentTooLarge          = errors.New("crypto/rsa: public exponent too large")
)
