// Code generated by lcryptogen from go1.27.1 src/crypto/internal/fips140/rsa/rsa.go. DO NOT EDIT.

// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package rsa

import (
	"errors"
	"github.com/soypat/lcrypto/internal/std/bigmod"
)

type PublicKey struct {
	N *bigmod.Modulus
	E int

	scratch scratchPublicKey
}

// scratchPublicKey holds locals hoisted out of function frames by lcryptogen
// so that they are never heap allocated. Not safe for concurrent use.
type scratchPublicKey struct {
	nat bigmod.Nat
}

// Size returns the modulus size in bytes. Raw signatures and ciphertexts
// for or by this public key will have the same size.
func (pub *PublicKey) Size() int {
	return (pub.N.BitLen() + 7) / 8
}

func checkPublicKey(pub *PublicKey) (fipsApproved bool, err error) {
	fipsApproved = true
	if pub.N == nil {
		return false, errMissingPublicModulus
	}
	natObj := &pub.scratch.nat
	*natObj = bigmod.Nat{}
	if pub.N.NatInto(natObj).IsOdd() == 0 {
		return false, errPublicModulusIsEven
	}
	// FIPS 186-5, Section 5.1: "This standard specifies the use of a modulus
	// whose bit length is an even integer and greater than or equal to 2048
	// bits."
	if pub.N.BitLen() < 2048 {
		fipsApproved = false
	}
	if pub.N.BitLen()%2 == 1 {
		fipsApproved = false
	}
	if pub.E < 2 {
		return false, errPublicExponentTooSmallOr
	}
	// e needs to be coprime with p-1 and q-1, since it must be invertible
	// modulo λ(pq). Since p and q are prime, this means e needs to be odd.
	if pub.E&1 == 0 {
		return false, errPublicExponentIsEven
	}
	// FIPS 186-5, Section 5.5(e): "The exponent e shall be an odd, positive
	// integer such that 2¹⁶ < e < 2²⁵⁶."
	if pub.E <= 1<<16 {
		fipsApproved = false
	}
	// We require pub.E to fit into a 32-bit integer so that we
	// do not have different behavior depending on whether
	// int is 32 or 64 bits. See also
	// https://www.imperialviolet.org/2012/03/16/rsae.html.
	if pub.E > 1<<31-1 {
		return false, errPublicExponentTooLarge
	}
	return fipsApproved, nil
}

var ErrMessageTooLong = errors.New("crypto/rsa: message too long for RSA key size")
var ErrVerification = errors.New("crypto/rsa: verification error")
