// Code generated by lcryptogen: errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/nistec/fiat. DO NOT EDIT.

package fiat

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errInvalidP256ElementEncoding = errors.New("invalid P256Element encoding")
	errInvalidP384ElementEncoding = errors.New("invalid P384Element encoding")
)
