// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen from go1.27.1 src/crypto/internal/fips140/ecdh/order_test.go. DO NOT EDIT.

// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ecdh

import (
	"bytes"
	"crypto/elliptic"
	"testing"
)

func TestOrders(t *testing.T) {
	if !bytes.Equal(elliptic.P256().Params().N.Bytes(), p256Order) {
		t.Errorf("P-256 order mismatch")
	}
}
