// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen errors.New calls hoisted from go1.27.1 src/crypto/internal/fips140/edwards25519. DO NOT EDIT.

package edwards25519

import "errors"

// Errors hoisted out of function bodies so returning them does not allocate.
var (
	errInvalidPointEncodingLength             = errors.New("edwards25519: invalid point encoding length")
	errInvalidPointEncoding                   = errors.New("edwards25519: invalid point encoding")
	errInvalidSetUniformBytesInputLength      = errors.New("edwards25519: invalid SetUniformBytes input length")
	errInvalidScalarLength                    = errors.New("invalid scalar length")
	errInvalidScalarEncoding                  = errors.New("invalid scalar encoding")
	errInvalidSetBytesWithClampingInputLength = errors.New("edwards25519: invalid SetBytesWithClamping input length")
)
