// DO NOT EDIT; generated by lcryptogen with `lcryptogen generate`.
// Code generated by lcryptogen allocation-free variants of functions in go:crypto/internal/fips140/edwards25519. DO NOT EDIT.

package edwards25519

// NewIdentityPointInto is the allocation-free [NewIdentityPoint]: it initializes into instead of a new Point.
func NewIdentityPointInto(into *Point) *Point {
	*into = Point{}
	return into.Set(identity)
}

// NewGeneratorPointInto is the allocation-free [NewGeneratorPoint]: it initializes into instead of a new Point.
func NewGeneratorPointInto(into *Point) *Point {
	*into = Point{}
	return into.Set(generator)
}

// BytesTo is the allocation-free [Point.Bytes]: it writes into out, which the
// result aliases, instead of a new array.
func (v *Point) BytesTo(out *[32]byte) []byte {
	return v.bytes(out)
}

// NewScalarInto is the allocation-free [NewScalar]: it initializes into instead of a new Scalar.
func NewScalarInto(into *Scalar) *Scalar {
	*into = Scalar{}
	return into
}

// BytesTo is the allocation-free [Scalar.Bytes]: it writes into out, which the
// result aliases, instead of a new array.
func (s *Scalar) BytesTo(out *[32]byte) []byte {
	return s.bytes(out)
}
